version: '3.6'

services:
    splunk:
        image: splunk/splunk:8.0.4
        container_name: splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_PASSWORD=changeme
        ports:
            - 8000:8000
            - 8088:8088
            - 8089:8089
        volumes:
            - ./splunk.yml:/tmp/defaults/default.yml
