name: Basic Checks

on: [push]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: nodeModules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      nodeModules-
            - name: Install dependencies
              run: yarn install --frozen-lockfile
              env:
                  CI: true
            - name: Check code
              run: |
                  yarn format:verify
                  yarn lint
              env:
                  CI: true
            - name: Build
              run: yarn build
              env:
                  CI: true
            - name: Test
              run: yarn test
              env:
                  CI: true
